# Docker Compose for development with live reload
version: '3.8'

services:
  # FastAPI application in development mode
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db
      - SECRET_KEY=development-secret-key-change-in-production
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:8080
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - RELOAD=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  # Mount source code for live reload
      - /app/.venv  # Exclude virtual environment
    networks:
      - fastapi-network
    command: ["python", "main.py"]

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastapi-network

volumes:
  postgres_data_dev:

networks:
  fastapi-network:
    driver: bridge
